### ISSUE TITLE
Using deprecated `module()` function

### ISSUE THREAD

**Issue by psliwka** [berlam/awesome-upower-battery#1]
Hi,

on my system (Debian Sid, awesome 4.2, Lua 5.3.3), awesome-upower-battery causes awesome to crash at startup with following error message:
```
[...]/.config/awesome/awesome-upower-battery/init.lua:6: attempt to call a nil value (global 'module')
```

As I understand from [here](http://www.luafaq.org/#T8.1.5), the `module()` function has been deprecated, and an [alternative module writing style](http://www.luafaq.org/#T1.37.2) is recommended instead.

**Comment by berlam** [comment]
Thank you @psliwka for the hint. I slightly refactored the widget in fc089cb674741ab928756c47946f72ce73ec3174 and you might kindly check, if it also works for you.

**Comment by psliwka** [comment]
Thank you for the fix, @berlam. I can confirm it resolves mentioned issue for me. Unfortunately however, I believe it introduced a regression in `settings` property handling, which I described in [this comment](https://github.com/berlam/awesome-upower-battery/commit/fc089cb674741ab928756c47946f72ce73ec3174#commitcomment-25556979). Would you mind checking it out?
